[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "base"
version = "0.1.0"
description = "base development environment"
readme = "README.md"
requires-python = ">=3.12.0"

dependencies = [
  "torch",
  "torchvision",
  "torchaudio",
  "ultralytics",
  "debugpy",
  "neovim",
  "openvino",
  "onnxruntime",
]

[tool.setuptools]
packages = []


